### PR TITLE
fix: allow dialling ip6 webtransport addresses

### PR DESCRIPTION
**Pull request by SgtPooki**
- fix: use valid rfc3986 ipv6 host syntax

### CODE REVIEW

**Review by achingbrain — CHANGES_REQUESTED** [review]
Can you add some tests please?

**Comment by achingbrain** [comment]
Just seen this in the wild I think:

```
Error: Failed to construct 'WebTransport': The URL 'https://2001:818:e338:5300:4a21:bff:fe2e:bc0:34001/.well-known/libp2p-webtransport?type=noise' is invalid.
at WebTransport.dial...
```

**Review by achingbrain — APPROVED** [review]

**Comment by MarcoPolo** [comment]
Isn't this going to be an issue anywhere we dial ipv6 addresses?

**Comment by SgtPooki** [comment]
> Isn't this going to be an issue anywhere we dial ipv6 addresses?

With JS, yep. The URL constructor requires the brackets for ip6

**Pull request merged**
